### ISSUE TITLE
running run_custom.py on our own images -- how to exactly set the z_far?    File "run_custom.py", line 103, in run_one_video     tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)   File "/home/mona/BundleSDF/bundlesdf.py", line 533, in run     valid = (depth>=0.1) & (mask>0)

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#101]
I get this error. I checked the other related issue but it's not fully clear to me how to resolve this issue. Could you please suggest a fix?
https://github.com/NVlabs/BundleSDF/issues/4

```
(py38) root@mona-ThinkStation-P7:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /home/mona/BundleSDF/green/ --out_folder /home/mona/BundleSDF/green/out --use_segmenter 1 --use_gui 1 --debug_level 2 
[2023-10-10 13:05:41.410] [warning] [Bundler.cpp:49] Connected to nerf_port 9999
[2023-10-10 13:05:41.411] [warning] [FeatureManager.cpp:2084] Connected to port 5555
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
GUI started
[bundlesdf.py] percentile denoise start
Traceback (most recent call last):
  File "run_custom.py", line 223, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 103, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/mona/BundleSDF/bundlesdf.py", line 533, in run
    valid = (depth>=0.1) & (mask>0)
ValueError: operands could not be broadcast together with shapes (480,640) (480,640,3) 
Process Process-2:
Process Process-3:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mona/BundleSDF/bundlesdf.py", line 37, in run_gui
    if gui_dict['join']:
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mona/BundleSDF/bundlesdf.py", line 89, in run_nerf
    join = p_dict['join']
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-10-10 13:05:46.123] [warning] [Bundler.cpp:59] Destructor

```

Here's two samples from my rgb and depth custom data:
```
(base) mona@mona-ThinkStation-P7:~/BundleSDF$ mediainfo /home/mona/BundleSDF/green/rgb/0000066.png 
General
Complete name                            : /home/mona/BundleSDF/green/rgb/0000066.png
CompleteName_Last                        : /home/mona/BundleSDF/green/rgb/0000321.png
Format                                   : PNG
Format/Info                              : Portable Network Graphic
File size                                : 27.9 MiB

Video
Format                                   : PNG
Format/Info                              : Portable Network Graphic
Format_Compression                       : Deflate
Width                                    : 640 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Color space                              : RGB
Bit depth                                : 8 bits
Compression mode                         : Lossless
Stream size                              : 27.9 MiB (100%)


(base) mona@mona-ThinkStation-P7:~/BundleSDF$ mediainfo /home/mona/BundleSDF/green/depth/0000066.png 
General
Complete name                            : /home/mona/BundleSDF/green/depth/0000066.png
CompleteName_Last                        : /home/mona/BundleSDF/green/depth/0000321.png
Format                                   : PNG
Format/Info                              : Portable Network Graphic
File size                                : 2.30 MiB

Video
Format                                   : PNG
Format/Info                              : Portable Network Graphic
Format_Compression                       : Deflate
Width                                    : 640 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Color space                              : Y
Bit depth                                : 16 bits
Compression mode                         : Lossless
Stream size                              : 2.30 MiB (100%)

```

![Screenshot from 2023-10-11 08-40-04](https://github.com/NVlabs/BundleSDF/assets/1892917/de4d4648-32f8-4065-a592-d4a6cb89e98b)

![0000066](https://github.com/NVlabs/BundleSDF/assets/1892917/6f166f4e-b41f-4ab7-aa6b-f2eb08c39ae2)

also, this line in run_custom.py is set to 480 which matches my custom images taken from a video stream from Intel RealSense 435.

`reader = YcbineoatReader(video_dir=video_dir, shorter_side=480)`

After I did the simultaneous depth and rgb capture using intel realsense camera 435, I used this script to convert depth images from 8 bit to 16 bit
```
# convert 8bit depth image to 16bit depth image

import cv2
import numpy as np
import glob


directory = '/home/mona/XMem/workspace/V00P00A00C00/depth_images/*.png'
depth_image_files = glob.glob(directory)  # Change the file extension if necessary
print('depth image file count: ', len(depth_image_files))
print('depth_image_files: ', depth_image_files)
for depth_image_file in depth_image_files:
    # Read the 8-bit depth image
    depth_8bit = cv2.imread(depth_image_file, cv2.IMREAD_GRAYSCALE)

    # Convert the 8-bit depth image to 16-bit depth image
    depth_16bit = (depth_8bit * 1000).astype(np.uint16)
    cv2.imwrite(depth_image_file, depth_16bit)

```

Using this script, I can the range of values in depth images from your milk data and my custom green ball data (and they are very different):

```
import cv2
import numpy as np
import glob


# directory = "/home/mona/BundleSDF/green/depth/*.png"  
directory = "/home/mona/BundleSDF/milk/2022-11-18-15-10-24_milk/depth/*.png"

depth_image_files = glob.glob(directory)


min_depth = np.inf
max_depth = -np.inf


for depth_image_file in depth_image_files:
    # Load a depth image
    depth_image = cv2.imread(depth_image_file, cv2.IMREAD_UNCHANGED)

   
    depth_values = depth_image.astype(np.float32)
    depth_values = depth_values * 0.001  # Convert from millimeters to meters

  
    current_min = np.min(depth_values)
    current_max = np.max(depth_values)
    min_depth = min(min_depth, current_min)
    max_depth = max(max_depth, current_max)


print("Minimum Depth:", min_depth, "m")
print("Maximum Depth:", max_depth, "m")
```

yours:
```
Minimum Depth: 0.0 m
Maximum Depth: 1.269 m
```

mine:
```
Minimum Depth: 0.0 m
Maximum Depth: 65.464005 m
```

Since it may be important, here is the script I use for capturing simultaneous video feeds for RGB and depth streams. Later, I used a slightly modified version of XMem for framing both depth and RGB  videos while segmenting the RGB video.

```
import pyrealsense2 as rs
import numpy as np
import cv2

pipeline = rs.pipeline()
config = rs.config()
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)

color_path = 'V00P00A00C00_rgb.avi'
depth_path = 'V00P00A00C00_depth.avi'

colorwriter = cv2.VideoWriter(color_path, cv2.VideoWriter_fourcc(*'XVID'), 30, (640,480), 1)
depthwriter = cv2.VideoWriter(depth_path, cv2.VideoWriter_fourcc(*'XVID'), 30, (640, 480), 8)

pipeline.start(config)
profile = pipeline.get_active_profile()
color_intrinsics = profile.get_stream(rs.stream.color).as_video_stream_profile().get_intrinsics()

try:
    while True:
        frames = pipeline.wait_for_frames()
        depth_frame = frames.get_depth_frame()
        color_frame = frames.get_color_frame()
        
        if not depth_frame or not color_frame:
            continue
        
        depth_image = np.asanyarray(depth_frame.get_data())
        color_image = np.asanyarray(color_frame.get_data())
        
        # Convert depth image to 8-bit
        depth_image_8bit = (depth_image / 256).astype(np.uint8)
        
        depth_image_rgb = cv2.cvtColor(depth_image_8bit, cv2.COLOR_GRAY2BGR)
        
        depthwriter.write(depth_image_rgb)
        colorwriter.write(color_image)
        
        cv2.imshow('Stream', color_image)
        
        if cv2.waitKey(1) == ord("q"):
            break
finally:
    colorwriter.release()
    depthwriter.release()

print("Color Intrinsics:")
print("Width:", color_intrinsics.width)
print("Height:", color_intrinsics.height)
print("Principal Point (x, y):", color_intrinsics.ppx, color_intrinsics.ppy)
print("Focal Length (x, y):", color_intrinsics.fx, color_intrinsics.fy)


pipeline.stop()
```

Is it possible for you to also share your script using which you get input data from realsense? @wenbowen123

**Comment by monajalal** [comment]
So the initial problem happened because I had RGB masks output by XMem and they had 3 channels I converted them to grayscale and reran the code with debug level 4 and got this error:
```
(py38) root@mona-ThinkStation-P7:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /home/mona/BundleSDF/green/ --out_folder /home/mona/BundleSDF/green/out --use_segmenter 1 --use_gui 1 --debug_level 4 
[2023-10-11 12:41:33.437] [warning] [Bundler.cpp:49] Connected to nerf_port 9999
[2023-10-11 12:41:33.437] [warning] [FeatureManager.cpp:2084] Connected to port 5555
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
GUI started
[bundlesdf.py] percentile denoise start
depth.shape (480, 640)
mask.shape (480, 640)
Traceback (most recent call last):
  File "run_custom.py", line 223, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 103, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/mona/BundleSDF/bundlesdf.py", line 536, in run
    thres = np.percentile(depth[valid], percentile)
  File "<__array_function__ internals>", line 200, in percentile
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4205, in percentile
    return _quantile_unchecked(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4473, in _quantile_unchecked
    return _ureduce(a,
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3752, in _ureduce
    r = func(a, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4639, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4745, in _quantile
    take(arr, indices=-1, axis=DATA_AXIS)
  File "<__array_function__ internals>", line 200, in take
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
Process Process-2:
Process Process-3:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mona/BundleSDF/bundlesdf.py", line 37, in run_gui
    if gui_dict['join']:
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mona/BundleSDF/bundlesdf.py", line 89, in run_nerf
    join = p_dict['join']
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-10-11 12:41:38.049] [warning] [Bundler.cpp:59] Destructor
(py38) root@mona-ThinkStation-P7:/home/mona/BundleSDF# 
```

**Comment by nikitasarawgi** [comment]
@monajalal 
I get the same error now. Were you able to fix this?

**Comment by mmalmeid** [comment]
I had this error. I caused it by running the `build.sh` from inside the dockerfile.
I removed the `RUN bash build.sh` from my dockerfile, rebuilt it, then ran `build.sh` inside the docker and the issue disappeared.
Not sure whether that's the case of any of you above, but this is what worked for me
