### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by cynthia-you** [NVlabs/BundleSDF#106]
sorry, when i run the script  "Run joint tracking and reconstruction"
i encountered error trace like: 
(py38) root@Fusion:/home/cy/bundlesdf/BundleSDF# python run_custom.py --mode run_video --video_dir 2022-11-18-15-10-24_milk --out_folder bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 1 --debug_level 2
[2023-10-27 00:46:56.178] [warning] [Bundler.cpp:49] Connected to nerf_port 9999
[2023-10-27 00:46:56.199] [warning] [FeatureManager.cpp:2084] Connected to port 5555
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
GUI started
[bundlesdf.py] percentile denoise start
[bundlesdf.py] percentile denoise done
[bundlesdf.py] processNewFrame start 1668813025164826994
[bundlesdf.py] process frame 1668813025164826994
[2023-10-27 00:47:43.685] [warning] [Bundler.cpp:268] Added frame 1668813025164826994 as keyframe, current #keyframe: 1
[bundlesdf.py] processNewFrame done 1668813025164826994
[bundlesdf.py] 1668813025164826994 prepare data for nerf
[bundlesdf.py] rematch_after_nerf: True
[2023-10-27 00:47:43.717] [warning] [Bundler.cpp:961] Welcome saveNewframeResult
[2023-10-27 00:47:44.469] [warning] [Bundler.cpp:1110] saveNewframeResult done
[bundlesdf.py] percentile denoise start
[bundlesdf.py] percentile denoise done
[bundlesdf.py] processNewFrame start 1668813025193228911
[bundlesdf.py] process frame 1668813025193228911
[bundlesdf.py] frame_pairs: 1
[loftr_wrapper.py] image0: torch.Size([1, 1, 400, 400])
[loftr_wrapper.py] net forward
Traceback (most recent call last):
  File "run_custom.py", line 223, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 103, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/cy/bundlesdf/BundleSDF/bundlesdf.py", line 543, in run
    self.process_new_frame(frame)
  File "/home/cy/bundlesdf/BundleSDF/bundlesdf.py", line 434, in process_new_frame
    self.find_corres([(frame, ref_frame)])
  File "/home/cy/bundlesdf/BundleSDF/bundlesdf.py", line 362, in find_corres
    corres = self.loftr.predict(rgbAs=imgs[::2], rgbBs=imgs[1::2])
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/cy/bundlesdf/BundleSDF/loftr_wrapper.py", line 68, in predict
    logging.info(f"mconf, {mconf.min()} {mconf.max()}")
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/core/_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
Process Process-3:
Process Process-2:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cy/bundlesdf/BundleSDF/bundlesdf.py", line 41, in run_gui
    if k in gui_dict:
  File "/home/cy/bundlesdf/BundleSDF/bundlesdf.py", line 96, in run_nerf
    if cnt_nerf==-1 and len(kf_to_nerf_list)<start_nerf_keyframes:
  File "<string>", line 2, in __contains__
  File "<string>", line 2, in __len__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 834, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
BrokenPipeError: [Errno 32] Broken pipe

Actually, i don't know why the BundleSDF report this error, i have wondered if it is because of the vpn. 
Could u help me with that ? plz~~~~~

**Comment by wenbowen123** [comment]
It seems like loftr failed. Can you make sure it loads the correct weights and the input RGBs are correct?
`"/home/cy/bundlesdf/BundleSDF/loftr_wrapper.py", line 68`
