### ISSUE TITLE
Pose file missing: {video_dir}

### ISSUE THREAD

**Issue by yigediao** [NVlabs/BundleSDF#143]
Hi, when I was runing the benchmark_ho3d.py, there is erro saying:
root@P16:/home/frank/BundleSDF-master# python benchmark_ho3d.py --video_dirs /home/frank/BundleSDF-master/HO3D_v3/evaluation/SM1  --out_dir /home/frank/SDF_output/ho3d_ours

 /home/frank/BundleSDF-master/HO3D_v3/evaluation/SM1
Traceback (most recent call last):
  File "benchmark_ho3d.py", line 157, in <module>
    out = benchmark_one_video(method, video_dir)
  File "benchmark_ho3d.py", line 31, in benchmark_one_video
    raise RuntimeError(f"Pose file missing: {video_dir}")

Can you help with this issue? Thank you.

**Comment by yigediao** [comment]
(py38) root@P16:/home/frank/BundleSDF-master# python benchmark_ho3d_2.py --video_dirs /home/frank/BundleSDF-master/HO3D_v3/evaluation/SM1 --out_dir /home/frank/debug/SDF_output/ho3d_ours


 /home/frank/BundleSDF-master/HO3D_v3/evaluation/SM1
Traceback (most recent call last):
  File "benchmark_ho3d_2.py", line 157, in <module>
    out = benchmark_one_video(method, video_dir)
  File "benchmark_ho3d_2.py", line 31, in benchmark_one_video
    raise RuntimeError(f"Pose file missing: {video_dir}")
RuntimeError: Pose file missing: /home/frank/BundleSDF-master/HO3D_v3/evaluation/SM1

**Comment by yigediao** [comment]
when I was running the "python run_ho3d.py ", there was an error:
[bundlesdf.py] frame_pairs: 27
[loftr_wrapper.py] image0: torch.Size([27, 1, 400, 400])
Traceback (most recent call last):
  File "run_ho3d.py", line 119, in <module>
    run_one_video(video_dir, args.out_dir)
  File "run_ho3d.py", line 64, in run_one_video
    tracker.run(color, depth, reader.K, id_str, mask=mask, occ_mask=None)
  File "/home/frank/BundleSDF-master/bundlesdf.py", line 543, in run
    self.process_new_frame(frame)
  File "/home/frank/BundleSDF-master/bundlesdf.py", line 494, in process_new_frame
    self.find_corres(pairs)
  File "/home/frank/BundleSDF-master/bundlesdf.py", line 362, in find_corres
    corres = self.loftr.predict(rgbAs=imgs[::2], rgbBs=imgs[1::2])
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/frank/BundleSDF-master/loftr_wrapper.py", line 50, in predict
    self.matcher(tmp)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/frank/BundleSDF-master/BundleTrack/LoFTR/src/loftr/loftr.py", line 49, in forward
    feats_c, feats_f = self.backbone(torch.cat([data['image0'], data['image1']], dim=0))
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/frank/BundleSDF-master/BundleTrack/LoFTR/src/loftr/backbone/resnet_fpn.py", line 116, in forward
    x1_out = self.layer1_outconv2(x1_out+x2_out_2x)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/frank/BundleSDF-master/bundlesdf.py", line 89, in run_nerf
    join = p_dict['join']
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by wenbowen123** [comment]
From [this](https://stackoverflow.com/questions/61467751/unable-to-find-a-valid-cudnn-algorithm-to-run-convolution), seems like you are running OOM. What's your GPU memory?
