### ISSUE TITLE
How to run BundleSDF on high resolution video?

### ISSUE THREAD

**Issue by kgg012392** [NVlabs/BundleSDF#173]
I want to run BundleSDF on custom data of high resolution (e.g. 720x1080). If I follow [this instruction](https://github.com/NVlabs/BundleSDF?tab=readme-ov-file#run-on-your-custom-data), I face the following error:
```
[2024-11-06 04:13:54.533] [warning] [Bundler.cpp:49] Connected to nerf_port 9999
[2024-11-06 04:13:54.534] [warning] [FeatureManager.cpp:2084] Connected to port 5555
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
[bundlesdf.py] percentile denoise start
Traceback (most recent call last):
  File "run_custom.py", line 223, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 103, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/xxx/BundleSDF/bundlesdf.py", line 533, in run
    valid = (depth>=0.1) & (mask>0)
ValueError: operands could not be broadcast together with shapes (480,720) (720,1080) 
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/BundleSDF/bundlesdf.py", line 89, in run_nerf
    join = p_dict['join']
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
[2024-11-06 04:13:59.089] [warning] [Bundler.cpp:59] Destructor
```
The above error can be reproduced on the example milk data if `rgb`, `masks` and `depths` files are upsampled to 720x1080 resolution. How should I properly run BundleSDF on high resolution video like this? What's the recommended video resolution?

**Comment by MichaelWangGo** [comment]
You should set a proper shorter_side which fits to your data in run_custom.py ` reader = YcbineoatReader(video_dir=video_dir, **shorter_side=1024**)`
