### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/_ckdtree.cpython-38-x86_64-linux-gnu.so)

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#2]
After building your docker from scratch, I get this error. Any hint? Do you expect it to work after the docker build is successful?

```
(py38) root@ard-gpu-01:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /milk/2022-11-18-15-10-24_milk/ --outfolder  /home/mona/BundleSDF/out_dir/ --use_segmenter 1 --use_gui 1 --debug_level 2
Traceback (most recent call last):
  File "run_custom.py", line 10, in <module>
    from bundlesdf import *
  File "/home/mona/BundleSDF/bundlesdf.py", line 10, in <module>
    from Utils import *
  File "/home/mona/BundleSDF/Utils.py", line 11, in <module>
    import open3d as o3d
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/__init__.py", line 146, in <module>
    import open3d.ml
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/ml/__init__.py", line 16, in <module>
    from . import datasets
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/ml/datasets.py", line 15, in <module>
    from open3d._ml3d.datasets import *
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/_ml3d/datasets/__init__.py", line 3, in <module>
    from .semantickitti import SemanticKITTI
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/_ml3d/datasets/semantickitti.py", line 6, in <module>
    from sklearn.neighbors import KDTree
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from .fixes import parse_version, threadpool_info
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 19, in <module>
    import scipy.stats
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/stats/__init__.py", line 485, in <module>
    from ._stats_py import *
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 39, in <module>
    from scipy.spatial.distance import cdist
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 105, in <module>
    from ._kdtree import *
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/_kdtree.py", line 4, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/_ckdtree.cpython-38-x86_64-linux-gnu.so)
```

```
(py38) root@ard-gpu-01:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /milk/2022-11-18-15-10-24_milk/ --outfolder  /home/mona/BundleSDF/out_dir/ --use_segmenter 1 --use_gui 1 --debug_level 2
Traceback (most recent call last):
  File "run_custom.py", line 10, in <module>
    from bundlesdf import *
  File "/home/mona/BundleSDF/bundlesdf.py", line 10, in <module>
    from Utils import *
  File "/home/mona/BundleSDF/Utils.py", line 11, in <module>
    import open3d as o3d
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/__init__.py", line 146, in <module>
    import open3d.ml
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/ml/__init__.py", line 16, in <module>
    from . import datasets
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/ml/datasets.py", line 15, in <module>
    from open3d._ml3d.datasets import *
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/_ml3d/datasets/__init__.py", line 3, in <module>
    from .semantickitti import SemanticKITTI
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/open3d/_ml3d/datasets/semantickitti.py", line 6, in <module>
    from sklearn.neighbors import KDTree
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 25, in <module>
    from .fixes import parse_version, threadpool_info
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 19, in <module>
    import scipy.stats
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/stats/__init__.py", line 485, in <module>
    from ._stats_py import *
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/stats/_stats_py.py", line 39, in <module>
    from scipy.spatial.distance import cdist
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 105, in <module>
    from ._kdtree import *
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/_kdtree.py", line 4, in <module>
    from ._ckdtree import cKDTree, cKDTreeNode
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/_ckdtree.cpython-38-x86_64-linux-gnu.so)
```

further I see these two as result of locate
```
/opt/conda/envs/py38/lib/libstdc++.so.6
/opt/conda/envs/py38/lib/libstdc++.so.6.0.29
```

My sys info:
```
(base) mona@ard-gpu-01:~$ uname -a
Linux ard-gpu-01 5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 x86_64 x86_64 GNU/Linux
(base) mona@ard-gpu-01:~$ lsb_release -a
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
(base) mona@ard-gpu-01:~$ gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) mona@ard-gpu-01:~$ g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(base) mona@ard-gpu-01:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
(base) mona@ard-gpu-01:~$ nvidia-smi
Thu Jun 22 09:56:13 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080 L...    On | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P3               N/A /  55W|      9MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2538      G   /usr/lib/xorg/Xorg                            4MiB |
|    0   N/A  N/A      2995      G   ...libexec/gnome-remote-desktop-daemon        3MiB |
+---------------------------------------------------------------------------------------+
```

As you see 3.4.29 is not shown below
```
(py38) root@ard-gpu-01:/home/mona/BundleSDF# strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by monajalal** [comment]
I may be wrong but it seems that issue is resolved by installing scipy via conda
```
(py38) root@ard-gpu-01:/home/mona/BundleSDF# conda install scipy
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/py38

  added / updated specs:
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2023.5.7           |     pyhd8ed1ab_0         149 KB  conda-forge
    libblas-3.9.0              |   12_linux64_mkl          12 KB  conda-forge
    libcblas-3.9.0             |   12_linux64_mkl          12 KB  conda-forge
    liblapack-3.9.0            |   12_linux64_mkl          12 KB  conda-forge
    python_abi-3.8             |           3_cp38           6 KB  conda-forge
    scipy-1.8.1                |   py38h1ee437e_0        25.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        25.2 MB

The following NEW packages will be INSTALLED:

  libblas            conda-forge/linux-64::libblas-3.9.0-12_linux64_mkl 
  libcblas           conda-forge/linux-64::libcblas-3.9.0-12_linux64_mkl 
  liblapack          conda-forge/linux-64::liblapack-3.9.0-12_linux64_mkl 
  python_abi         conda-forge/linux-64::python_abi-3.8-3_cp38 

The following packages will be UPDATED:

  ca-certificates    anaconda::ca-certificates-2023.01.10-~ --> conda-forge::ca-certificates-2023.5.7-hbcca054_0 
  certifi            anaconda/linux-64::certifi-2022.12.7-~ --> conda-forge/noarch::certifi-2023.5.7-pyhd8ed1ab_0 

The following packages will be SUPERSEDED by a higher-priority channel:

  scipy               anaconda::scipy-1.10.0-py38h14f4228_0 --> conda-forge::scipy-1.8.1-py38h1ee437e_0 


Proceed ([y]/n)? y


Downloading and Extracting Packages
                                                                                                                                                                                       
Preparing transaction: done                                                                                                                                                            
Verifying transaction: done                                                                                                                                                            
Executing transaction: done                                                                                                                                                            
(py38) root@ard-gpu-01:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /milk/2022-11-18-15-10-24_milk/ --outfolder  /home/mona/BundleSDF/out_dir/ --use_segmenter 1 --use_gui 1 --debug_level 2                                                                                                                                                       
Traceback (most recent call last):
  File "run_custom.py", line 10, in <module>
    from bundlesdf import *
  File "/home/mona/BundleSDF/bundlesdf.py", line 15, in <module>
    import my_cpp
ModuleNotFoundError: No module named 'my_cpp'
```

**Comment by monajalal** [comment]
@bkyCadida I had that problem too and I cannot remember how I exactly solved it but from the history dump I believe I uninstalled scipy, numpy, and installed these

```
  173  strings /opt/conda/envs/py38/lib/libstdc++.so.6 | grep GLIBCXX
  174  pip show scipy
  175  pip uninstall scipy
  177  pip install scipy
  179  pip show numpy
  182  pip uninstall numpy
  183  pip install numpy
  189  pip install six
```

Based on command 173, 3.4.30 was not shown so I had to reinstall scipy again. Also uninstall the conda version.

**Comment by bkyCadida** [comment]
Thanks @monajalal 
In the meantime I tried the solution posted here https://stackoverflow.com/a/74366512 which solved this problem, though I haven't tried yours. I'll keep it in mind for next time!
