### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by bkyCadida** [NVlabs/BundleSDF#22]
I get the following error when trying to run the example milk data:
` python run_custom.py --mode run_video --video_dir /home/bastian/BundleSDF/2022-11-18-15-10-24_milk --out_folder /home/bastian/BundleSDF/outdir/bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 0 --debug_level 2
[2023-06-28 04:46:10.905] [warning] [Bundler.cpp:49] Connected to nerf_port 9999
[2023-06-28 04:46:10.909] [warning] [FeatureManager.cpp:2084] Connected to port 5555
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
[bundlesdf.py] percentile denoise start
[bundlesdf.py] percentile denoise done
[bundlesdf.py] processNewFrame start 1668813025164826994
[bundlesdf.py] process frame 1668813025164826994
[2023-06-28 04:46:14.748] [warning] [Bundler.cpp:268] Added frame 1668813025164826994 as keyframe, current #keyframe: 1
[bundlesdf.py] processNewFrame done 1668813025164826994
[bundlesdf.py] 1668813025164826994 prepare data for nerf
[bundlesdf.py] rematch_after_nerf: True
[2023-06-28 04:46:14.759] [warning] [Bundler.cpp:961] Welcome saveNewframeResult
[2023-06-28 04:46:14.880] [warning] [Bundler.cpp:1110] saveNewframeResult done
[bundlesdf.py] percentile denoise start
[bundlesdf.py] percentile denoise done
[bundlesdf.py] processNewFrame start 1668813025193228911
[bundlesdf.py] process frame 1668813025193228911
[bundlesdf.py] frame_pairs: 1
[loftr_wrapper.py] image0: torch.Size([1, 1, 400, 400])
[loftr_wrapper.py] net forward
Traceback (most recent call last):
  File "run_custom.py", line 203, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 103, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/bastian/BundleSDF/bundlesdf.py", line 543, in run
    self.process_new_frame(frame)
  File "/home/bastian/BundleSDF/bundlesdf.py", line 434, in process_new_frame
    self.find_corres([(frame, ref_frame)])
  File "/home/bastian/BundleSDF/bundlesdf.py", line 362, in find_corres
    corres = self.loftr.predict(rgbAs=imgs[::2], rgbBs=imgs[1::2])
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/bastian/BundleSDF/loftr_wrapper.py", line 68, in predict
    logging.info(f"mconf, {mconf.min()} {mconf.max()}")
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bastian/BundleSDF/bundlesdf.py", line 89, in run_nerf
    join = p_dict['join']
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-06-28 04:46:16.693] [warning] [Bundler.cpp:59] Destructor`

I followed instructions from here https://github.com/NVlabs/BundleSDF/issues/15#issue-1775498112 to resolve the earlier issue, otherwise I followed the instructions from the Readme.

Also I haven't seen this error on other machines.

Any ideas?

**Comment by wenbowen123** [comment]
you mean you didn't have this error on some other machines? Can you provide more details on the machines?

**Comment by bkyCadida** [comment]
Sure!
Host:
Windows 10, Build 19045.3086
32 GB Ram, AMD Ryzen 7 3700X 8-Core
NVIDIA Geforce GTX 1660 Super 
latest Docker Desktop, latest NVIDIA Driver
nvidia-smi:

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.04              Driver Version: 536.23       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1660 ...    On  | 00000000:09:00.0  On |                  N/A |
| 28%   40C    P8               6W / 125W |    367MiB /  6144MiB |      2%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

Even if the graphics card is not big enough eventually, I should not get this error right after starting the program.

**Comment by wenbowen123** [comment]
The error seems coming from [LoFTR](https://github.com/zju3dv/LoFTR). Maybe you can try if your machine can run it? Also we recommend more recent GPUs such as 30XX, 40XX
