### ISSUE TITLE
BundleSDF/bundlesdf.py", line 15, in <module>     import my_cpp ModuleNotFoundError: No module named 'my_cpp'

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#3]
I didn't get any error building the docker but I get an error running the following:

```
(py38) root@ard-gpu-01:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /milk/2022-11-18-15-10-24_milk/ --outfolder  /home/mona/BundleSDF/out_dir/ --use_segmenter 1 --use_gui 1 --debug_level 2
Traceback (most recent call last):
  File "run_custom.py", line 10, in <module>
    from bundlesdf import *
  File "/home/mona/BundleSDF/bundlesdf.py", line 15, in <module>
    import my_cpp
ModuleNotFoundError: No module named 'my_cpp'
```

```
(py38) root@ard-gpu-01:/home/mona/BundleSDF# rg my_cpp
bundlesdf.py
15:import my_cpp
316:    yml = my_cpp.YamlLoadFile(cfg_track_dir)
317:    self.bundler = my_cpp.Bundler(yml)
344:    frame = my_cpp.Frame(color,depth,roi,pose_in_model,self.cnt,id_str,K,self.bundler.yml)
346:      frame._fg_mask = my_cpp.cvMat(mask)
348:      frame._occ_mask = my_cpp.cvMat(occ_mask)
375:      self.bundler._newframe._status = my_cpp.Frame.FAIL
412:      frame._status = my_cpp.Frame.FAIL;
423:      frame._status = my_cpp.Frame.FAIL
437:    if frame._status==my_cpp.Frame.FAIL:
446:        visible = my_cpp.computeCovisibility(frame, kf)
468:        frame._status = my_cpp.Frame.FAIL
495:    if frame._status==my_cpp.Frame.FAIL:
502:    if frame._status==my_cpp.Frame.FAIL:

BundleTrack/CMakeLists.txt
118:# pybind11_add_module(my_cpp pybind_interface/pybind_api.cpp ${MY_SRC})
119:pybind11_add_module(my_cpp pybind_interface/pybind_api.cpp ${CMAKE_SOURCE_DIR}/src/Frame.cpp)
120:target_link_libraries(my_cpp PRIVATE ${PROJECT_NAME} MY_CUDA_LIB ${YAML_CPP_LIBRARIES} ${PYTHON_LIBRARIES} ${CUDA_LIBRARIES})

BundleTrack/pybind_interface/pybind_api.cpp
23:PYBIND11_MODULE(my_cpp, m)
```

**Comment by monajalal** [comment]
I redid making the my_cpp target but no luck.
```
   73  mkdir build
   74  cd build
   77  cmake ../BundleTrack/
   78  make my_cpp

/home/mona/BundleSDF/BundleTrack/src/Utils.h: In member function 'double Utils::Timer::elapsed()':
/home/mona/BundleSDF/BundleTrack/src/Utils.h:190:3: warning: no return statement in function returning non-void [-Wreturn-type]
  190 |   }
      |   ^
[ 80%] Building CXX object CMakeFiles/BundleTrack.dir/src/cuda/SIFTImageManager.cpp.o
[ 85%] Linking CXX shared library libBundleTrack.so
[ 85%] Built target BundleTrack
Scanning dependencies of target my_cpp
[ 90%] Building CXX object CMakeFiles/my_cpp.dir/pybind_interface/pybind_api.cpp.o
In file included from /home/mona/BundleSDF/BundleTrack/src/FeatureManager.h:30,
                 from /home/mona/BundleSDF/BundleTrack/pybind_interface/pybind_api.cpp:16:
/home/mona/BundleSDF/BundleTrack/src/Utils.h: In member function 'double Utils::Timer::elapsed()':
/home/mona/BundleSDF/BundleTrack/src/Utils.h:190:3: warning: no return statement in function returning non-void [-Wreturn-type]
  190 |   }
      |   ^
/home/mona/BundleSDF/BundleTrack/pybind_interface/pybind_api.cpp: In lambda function:
/home/mona/BundleSDF/BundleTrack/pybind_interface/pybind_api.cpp:76:7: warning: control reaches end of non-void function [-Wreturn-type]
   76 |       })
      |       ^
[ 95%] Building CXX object CMakeFiles/my_cpp.dir/src/Frame.cpp.o
In file included from /home/mona/BundleSDF/BundleTrack/src/Frame.h:17,
                 from /home/mona/BundleSDF/BundleTrack/src/Frame.cpp:12:
/home/mona/BundleSDF/BundleTrack/src/Utils.h: In member function 'double Utils::Timer::elapsed()':
/home/mona/BundleSDF/BundleTrack/src/Utils.h:190:3: warning: no return statement in function returning non-void [-Wreturn-type]
  190 |   }
      |   ^
[100%] Linking CXX shared module my_cpp.cpython-38-x86_64-linux-gnu.so
[100%] Built target my_cpp
```

Please let me know if you can help with a solution

**Comment by monajalal** [comment]
```
(py38) root@ard-gpu-01:/home/mona/BundleSDF/build# find . -name my_cpp.cpython-38-x86_64-linux-gnu.so
./my_cpp.cpython-38-x86_64-linux-gnu.so
(py38) root@ard-gpu-01:/home/mona/BundleSDF/build# ln -s my_cpp.cpython-38-x86_64-linux-gnu.so my_cpp.so
(py38) root@ard-gpu-01:/home/mona/BundleSDF# ls build
total 124M
drwxrwxr-x 11 1002 1002 4.0K Jun 22 08:46 ..
-rw-r--r--  1 root root 1.5K Jun 22 08:47 cmake_install.cmake
-rw-r--r--  1 root root  58K Jun 22 11:31 CMakeCache.txt
-rw-r--r--  1 root root 8.1K Jun 22 11:31 compile_commands.json
-rw-r--r--  1 root root  13K Jun 22 11:31 Makefile
-rwxr-xr-x  1 root root 9.4M Jun 22 11:31 libMY_CUDA_LIB.so
-rwxr-xr-x  1 root root 114M Jun 22 11:31 libBundleTrack.so
-rwxr-xr-x  1 root root 1.3M Jun 22 11:31 my_cpp.cpython-38-x86_64-linux-gnu.so
drwxr-xr-x 10 root root 4.0K Jun 22 11:31 CMakeFiles
lrwxrwxrwx  1 root root   37 Jun 22 11:33 my_cpp.so -> my_cpp.cpython-38-x86_64-linux-gnu.so
drwxr-xr-x  3 root root 4.0K Jun 22 11:33 .

```

add this end of ~/.bashrc and then source it:
`export PYTHONPATH=/home/mona/BundleSDF/build:$PYTHONPATH`

**Comment by assia855** [comment]
Hi @monajalal how did you solve it please

**Comment by wang-shuaikang** [comment]
my_cpp.cpython-38-x86_64-linux-gnu.so cannot find how to solve it
