### ISSUE TITLE
running bundlesdf on custom data -- image naming as well depth image format

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#31]
for depth image format, do you expect a certain format?
I am getting an error for the line starting with `thres`:
```
    percentile = self.cfg_track['depth_processing']["percentile"]
    if percentile<100:   # Denoise
      logging.info("percentile denoise start")
      valid = (depth>=0.1) & (mask>0)
      thres = np.percentile(depth[valid], percentile)
      depth[depth>=thres] = 0
      logging.info("percentile denoise done")
```

Here's how I run it:
```
(py38) root@bundlesdf:/home/azureuser/BundleSDF# python run_custom.py --mode run_video --video_dir /home/azureuser/BundleSDF/my_obj/V00P00A00C00 --out_folder /home/azureuser/BundleSDF/my_obj/out --use_segmenter 1 --use_gui 0 --debug_level 2
[2023-07-03 11:28:14.424] [warning] [Bundler.cpp:49] Connected to nerf_port 9999
[2023-07-03 11:28:14.424] [warning] [FeatureManager.cpp:2084] Connected to port 5555
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
[bundlesdf.py] percentile denoise start
Traceback (most recent call last):
  File "run_custom.py", line 205, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 105, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/azureuser/BundleSDF/bundlesdf.py", line 534, in run
    thres = np.percentile(depth[valid], percentile)
  File "<__array_function__ internals>", line 180, in percentile
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4166, in percentile
    return _quantile_unchecked(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4424, in _quantile_unchecked
    r, k = _ureduce(a,
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3725, in _ureduce
    r = func(a, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4593, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4699, in _quantile
    take(arr, indices=-1, axis=DATA_AXIS)
  File "<__array_function__ internals>", line 180, in take
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
[2023-07-03 11:28:19.309] [warning] [Bundler.cpp:59] Destructor
```

Also, my image names are like `0004487.png` for depth, rgb, masks folder. However, yours is timestamp. Is my naming format fine?

Here's an example of how my depth image looks like:
![0000079](https://github.com/NVlabs/BundleSDF/assets/1892917/ad0c4bd4-5e81-44e5-a28b-861d3d3122ba)

**Comment by monajalal** [comment]
@wenbowen123 

Can you please guide if you need a certain specification for mask or depth? I am using the mask format given to me by xmem and I am using the depth from intel realsense as shown above.

also, here is what I get:

(depth>=0.1):  [[[ True False False]

**Comment by wenbowen123** [comment]
Please find in [readme ](https://github.com/NVlabs/BundleSDF#run-on-your-custom-data)the details about the format. We also have the example data for reference.
