### ISSUE TITLE
Excuse me ,I can't find a file in this project

### ISSUE THREAD

**Issue by pla63850** [NVlabs/BundleSDF#41]
When I run the run_ho3d.py on Ubuntu terminal, I get the following error.

Traceback (most recent call last):
  File "run_ho3d.py", line 10, in <module>
    from bundlesdf import *
  File "/home/usopp/ccooddee/BundleSDF-master/bundlesdf.py", line 15, in <module>
    import my_cpp
ModuleNotFoundError: No module named 'my_cpp'

 I apologize for the inconvenience, but I'm unable to find the my_cpp

**Comment by assia855** [comment]
@pla63850 did you find it please?

**Comment by y200504040u** [comment]
Maybe you did not complete to build according to the Readme document.

**Comment by assia855** [comment]
Hi @y200504040u I already install docker as require in readme what should I do else please

**Comment by wenbowen123** [comment]
As mentioned in readme, you need to run `bash build.sh` inside docker
