### ISSUE TITLE
typo found and fixed

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#5]
```
(py38) root@ard-gpu-01:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /milk/2022-11-18-15-10-24_milk/ --out_folder  /home/mona/BundleSDF/out_dir/ --use_segmenter 1 --use_gui 1 --debug_level 2
[2023-06-22 11:39:24.897] [warning] [Bundler.cpp:49] Connected to nerf_port 9999
[2023-06-22 11:39:24.897] [warning] [FeatureManager.cpp:2084] Connected to port 5555
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
GUI started
libGL error: MESA-LOADER: failed to retrieve device information
Glfw Error 65543: GLX: Failed to create context: GLXBadFBConfig
python: /home/runner/work/DearPyGui/DearPyGui/thirdparty/glfw/src/window.c:533: glfwSetWindowPos: Assertion `window != NULL' failed.
Traceback (most recent call last):
  File "run_custom.py", line 203, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 86, in run_one_video
    mask = segmenter.run(color_file.replace('rgb','masks'))
  File "/home/mona/BundleSDF/segmentation_utils.py", line 18, in run
    return (cv2.imread(mask_file, -1)>0).astype(np.uint8)
NameError: name 'np' is not defined
Process Process-3:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mona/BundleSDF/bundlesdf.py", line 89, in run_nerf
    join = p_dict['join']
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-06-22 11:39:28.734] [warning] [Bundler.cpp:59] Destructor
(py38) root@ard-gpu-01:/home/mona/BundleSDF# vi /home/mona/BundleSDF/segmentation_utils.py
```

**Comment by monajalal** [comment]
![Screenshot from 2023-06-22 14-40-31](https://github.com/NVlabs/BundleSDF/assets/1892917/1c97a75f-fe42-4860-ba9d-4026e6bb2db7)
