### ISSUE TITLE
Problem with bash build.sh

### ISSUE THREAD

**Issue by wang-shuaikang** [NVlabs/BundleSDF#63]
(base) huangcheng@hc:~/hou/BundleSDF/BundleSDF-master$ bash build.sh
build.sh: 第 2 行: cd: /kaolin: 没有那个文件或目录
Obtaining file:///home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda
Installing collected packages: common
  Running setup.py develop for common
    ERROR: Command errored out with exit status 1:
     command: /home/huangcheng/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda/setup.py'"'"'; __file__='"'"'/home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda/
    Complete output (60 lines):
    /home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_cflags'
      warnings.warn(msg)
    /home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
      warnings.warn(msg)
    running develop
    /home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    creating common.egg-info
    writing common.egg-info/PKG-INFO
    writing dependency_links to common.egg-info/dependency_links.txt
    writing top-level names to common.egg-info/top_level.txt
    writing manifest file 'common.egg-info/SOURCES.txt'
    /home/huangcheng/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    reading manifest file 'common.egg-info/SOURCES.txt'
    writing manifest file 'common.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda/setup.py", line 21, in <module>
        setup(
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1214, in run_command
        super().run_command(command)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
        self._check_cuda_version(compiler_name, compiler_version)
      File "/home/huangcheng/anaconda3/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 812, in _check_cuda_version
        raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
    RuntimeError:
    The detected CUDA version (11.3) mismatches the version that was used to compile
    PyTorch (10.2). Please make sure to use the same CUDA versions.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/huangcheng/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda/setup.py'"'"'; __file__='"'"'/home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
CMake Error at CMakeLists.txt:10 (cmake_minimum_required):
  CMake 3.15 or higher is required.  You are running version 3.10.2

-- Configuring incomplete, errors occurred!

**Comment by wang-shuaikang** [comment]
(py38) root@hc:/home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda# pip install -e . -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda
  Preparing metadata (setup.py) ... done
Installing collected packages: common
  Running setup.py develop for common
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [90 lines of output]
        No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'
        running develop
        running egg_info
        writing common.egg-info/PKG-INFO
        writing dependency_links to common.egg-info/dependency_links.txt
        writing top-level names to common.egg-info/top_level.txt
        reading manifest file 'common.egg-info/SOURCES.txt'
        writing manifest file 'common.egg-info/SOURCES.txt'
        running build_ext
        building 'common' extension
        /opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'extra_cflags'
          warnings.warn(msg)
        /opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
          warnings.warn(msg)
        /opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda/setup.py", line 21, in <module>
            setup(
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
            self.install_for_development()
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
            self.run_command('build_ext')
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
            _build_ext.run(self)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
            self.build_extensions()
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
            build_ext.build_extensions(self)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
            self._build_extensions_serial()
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
            self.build_extension(ext)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
            _build_ext.build_extension(self, ext)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 127, in build_extension
            super(build_ext, self).build_extension(ext)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
            objects = self.compiler.compile(
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 557, in unix_wrap_ninja_compile
            cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 456, in unix_cuda_flags
            cflags + _get_cuda_arch_flags(cflags))
          File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
            arch_list[-1] += '+PTX'
        IndexError: list index out of range
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [90 lines of output]
    No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.3'
    running develop
    running egg_info
    writing common.egg-info/PKG-INFO
    writing dependency_links to common.egg-info/dependency_links.txt
    writing top-level names to common.egg-info/top_level.txt
    reading manifest file 'common.egg-info/SOURCES.txt'
    writing manifest file 'common.egg-info/SOURCES.txt'
    running build_ext
    building 'common' extension
    /opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'extra_cflags'
      warnings.warn(msg)
    /opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'extra_cuda_cflags'
      warnings.warn(msg)
    /opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/huangcheng/hou/BundleSDF/BundleSDF-master/mycuda/setup.py", line 21, in <module>
        setup(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 127, in build_extension
        super(build_ext, self).build_extension(ext)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
        objects = self.compiler.compile(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 557, in unix_wrap_ninja_compile
        cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 456, in unix_cuda_flags
        cflags + _get_cuda_arch_flags(cflags))
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
        arch_list[-1] += '+PTX'
    IndexError: list index out of range
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by wenbowen123** [comment]
it seems like you didn't run this in a docker env. Can you try that?

**Comment by wang-shuaikang** [comment]
Yes, I can run it in the docker environment, but when I first test the ho3d dataset, there is an error：
(py38) root@hc:/home/huangcheng/hou/BundleSDF/BundleSDF-master# python run_ho3d.py --video_dirs /home/huangcheng/hou/BundleSDF/BundleSDF-master/HO3D_v3/evaluation/MPM10 --out_dir /home/huangcheng/hou/BundleSDF/BundleSDF-master/ho3d_our
Traceback (most recent call last):
  File "run_ho3d.py", line 10, in &lt;module&gt;
    from bundlesdf import *
  File "/home/huangcheng/hou/BundleSDF/BundleSDF-master/bundlesdf.py", line 15, in &lt;module&gt;
    import my_cpp
ModuleNotFoundError: No module named 'my_cpp'

**Comment by wenbowen123** [comment]
you need to run `bash build.sh` in the docker container.
