### ISSUE TITLE
21 errors detected in the compilation of "/home/leo/BundleSDF/mycuda/torch_ngp_grid_encoder/gridencoder.cu"

### ISSUE THREAD

**Issue by Leo1121clean** [NVlabs/BundleSDF#67]
Hello, here I have met a problem, and I can't fix it for a few days.
My problem is appeared when running "bash build.sh."
The error information is shown below:

```
[2/2] c++ -MMD -MF /home/leo/BundleSDF/mycuda/build/temp.linux-x86_64-cpython-38/home/leo/BundleSDF/mycuda/torch_ngp_grid_encoder/bindings.o.d -pthread -B /opt/conda/envs/py38/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/envs/py38/include -fPIC -O2 -isystem /opt/conda/envs/py38/include -fPIC -I/opt/conda/envs/py38/lib/python3.8/site-packages/torch/include -I/opt/conda/envs/py38/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/envs/py38/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/envs/py38/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/local/include/eigen3 -I/usr/include/eigen3 -I/opt/conda/envs/py38/include/python3.8 -I/opt/conda/envs/py38/include/python3.8 -c -c /home/leo/BundleSDF/mycuda/torch_ngp_grid_encoder/bindings.cpp -o /home/leo/BundleSDF/mycuda/build/temp.linux-x86_64-cpython-38/home/leo/BundleSDF/mycuda/torch_ngp_grid_encoder/bindings.o -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=gridencoder -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
        subprocess.run(
      File "/opt/conda/envs/py38/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/home/leo/BundleSDF/mycuda/setup.py", line 21, in <module>
        setup(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/dist.py", line 1234, in run_command
        super().run_command(command)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
        self.build_extensions()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 127, in build_extension
        super(build_ext, self).build_extension(ext)
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
        objects = self.compiler.compile(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
-- The CUDA compiler identification is NVIDIA 11.3.109
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_CXX_COMPILER_VERSION: 9.4.0
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: system program_options serialization 
-- Checking for module 'eigen3'
--   Found eigen3, version 3.4.0
-- Found Eigen: /usr/local/include/eigen3 (Required is at least version "3.1") 
-- Eigen found (include: /usr/local/include/eigen3, version: 3.4.0)
-- Found Boost: /usr/include (found suitable version "1.71.0", minimum required is "1.55.0") found components: system filesystem date_time iostreams serialization regex 
-- Checking for module 'flann'
--   Found flann, version 1.9.1
-- Found FLANN: /usr/lib/x86_64-linux-gnu/libflann_cpp.so  
CMake Warning at /usr/local/share/pcl-1.10/PCLConfig.cmake:271 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/local/share/pcl-1.10/PCLConfig.cmake:330 (find_VTK)
  /usr/local/share/pcl-1.10/PCLConfig.cmake:535 (find_external_library)
  CMakeLists.txt:41 (find_package)


** WARNING ** 2d features related to vtk will be disabled
** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
CMake Warning at /usr/local/share/pcl-1.10/PCLConfig.cmake:271 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/local/share/pcl-1.10/PCLConfig.cmake:330 (find_VTK)
  /usr/local/share/pcl-1.10/PCLConfig.cmake:535 (find_external_library)
  CMakeLists.txt:41 (find_package)
```

I would be very grateful if anyone could help me solve this problem! Thank you!

**Comment by wenbowen123** [comment]
did you run inside a docker container?

**Comment by Leo1121clean** [comment]
@wenbowen123 yeah, I ran it in the container you provided. All settings were the same as the tutorial, but this error appeared...

**Comment by wenbowen123** [comment]
@Leo1121clean did you run on Windows or Ubuntu?

**Comment by wskguyue** [comment]
I have the same problem as you. Have you solved your problem

**Comment by Jekyll6104** [comment]
I have the same problem as you, I am running in the docker container of ubuntu20.04, is there any way to solve it

**Comment by Leo1121clean** [comment]
@wenbowen123 sorry for responding late. I ran it in Ubuntu 20.04 and also in the container you provided. 
Yesterday I ran it on another better computer in the same way and succeded.
I guess whether it is related to GPU version? My computer in GTX 750 ti, and the better one is GTX 2080 ti.

**Comment by wenbowen123** [comment]
@Leo1121clean The GPU seems the cause. Thanks for reporting back!
