### ISSUE TITLE
Potential broken dependency or CMakeLists.txt file --   File "/home/mona/BundleSDF/mycuda/torch_ngp_grid_encoder/grid.py", line 23, in <module>     import gridencoder ModuleNotFoundError: No module named 'gridencoder'

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#7]
```
(py38) root@ard-gpu-01:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /milk/2022-11-18-15-10-24_milk/ --out_folder  /home/mona/BundleSDF/out_dir/ --use_segmenter 1 --use_gui 0 --debug_level 2

txt 

[2023-06-22 19:05:17.850] [warning] [FeatureManager.cpp:1589] start multi pair ransac GPU, pairs#=1
[2023-06-22 19:05:17.851] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813028667811894 #inliers=566, #prev 699
[bundlesdf.py] frame 1668813028705557007 pose update before
[[ 0.969 -0.184  0.168 -0.132]
 [ 0.199  0.977 -0.078 -0.07 ]
 [-0.15   0.109  0.983 -0.417]
 [ 0.     0.     0.     1.   ]]
[2023-06-22 19:05:17.853] [warning] [FeatureManager.cpp:1095] procrustesByCorrespondence err per point between 1668813028705557007 and 1668813028667811894: 0.000136082
[bundlesdf.py] frame 1668813028705557007 pose update after
[[ 0.967 -0.188  0.173 -0.136]
 [ 0.204  0.975 -0.083 -0.068]
 [-0.153  0.115  0.981 -0.416]
 [ 0.     0.     0.     1.   ]]
[2023-06-22 19:05:17.854] [warning] [Bundler.cpp:67] forgetting frame 1668813028470606334
[2023-06-22 19:05:17.854] [warning] [FeatureManager.cpp:469] forgetting frame 1668813028470606334
[bundlesdf.py] exceed window size, forget frame 1668813028470606334
[2023-06-22 19:05:17.854] [warning] [Bundler.cpp:435] total keyframes=4, want to select 10
[2023-06-22 19:05:17.854] [warning] [Bundler.cpp:793] frame 1668813028705557007 and 1668813025164826994 visible=0.878109
[2023-06-22 19:05:17.854] [warning] [Bundler.cpp:802] add frame (1668813028705557007, 1668813025164826994) into pairs
[2023-06-22 19:05:17.854] [warning] [Bundler.cpp:793] frame 1668813028705557007 and 1668813026867024573 visible=0.86201
[2023-06-22 19:05:17.854] [warning] [Bundler.cpp:802] add frame (1668813028705557007, 1668813026867024573) into pairs
[2023-06-22 19:05:17.855] [warning] [Bundler.cpp:793] frame 1668813028705557007 and 1668813028304456241 visible=0.845315
[2023-06-22 19:05:17.855] [warning] [Bundler.cpp:802] add frame (1668813028705557007, 1668813028304456241) into pairs
[2023-06-22 19:05:17.855] [warning] [Bundler.cpp:793] frame 1668813028705557007 and 1668813028571340409 visible=0.873254
[2023-06-22 19:05:17.855] [warning] [Bundler.cpp:802] add frame (1668813028705557007, 1668813028571340409) into pairs
[bundlesdf.py] frame_pairs: 4
[loftr_wrapper.py] image0: torch.Size([4, 1, 400, 400])
[loftr_wrapper.py] net forward
[loftr_wrapper.py] mconf, 0.20000934600830078 0.9887229800224304
[loftr_wrapper.py] pair_ids (1625,)
[loftr_wrapper.py] corres: (1625, 5)
[2023-06-22 19:05:18.012] [warning] [FeatureManager.cpp:1589] start multi pair ransac GPU, pairs#=4
[2023-06-22 19:05:18.023] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813025164826994 #inliers=156, #prev 279
[2023-06-22 19:05:18.023] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813026867024573 #inliers=143, #prev 294
[2023-06-22 19:05:18.023] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813028304456241 #inliers=173, #prev 284
[2023-06-22 19:05:18.023] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813028571340409 #inliers=361, #prev 463
#optimizeGPU frames=5, #keyframes=4, #_frames=10
1668813025164826994 1668813026867024573 1668813028304456241 1668813028571340409 1668813028705557007 
[2023-06-22 19:05:18.031] [warning] [Bundler.cpp:920] OptimizerGPU begin, global_corres#=2962
global_corres=2962
maxNumResiduals / maxNumberOfImages = 50962 / 5 = 10192
m_maxNumberOfImages*m_maxCorrPerImage = 5 x 1313 = 6565
m_solver->solve Time difference = 10.673[ms]
[2023-06-22 19:05:18.044] [warning] [Bundler.cpp:924] OptimizerGPU finish
[2023-06-22 19:05:18.046] [warning] [Bundler.cpp:320] Added frame 1668813028705557007 as keyframe, current #keyframe: 5
[bundlesdf.py] processNewFrame done 1668813028705557007
[bundlesdf.py] 1668813028705557007 prepare data for nerf
[bundlesdf.py] out_dir: /home/mona/BundleSDF/out_dir///1668813028705557007/nerf
[tool.py] compute_scene_bounds_worker start
[tool.py] compute_scene_bounds_worker done
[tool.py] merge pcd
[tool.py] compute_translation_scales done
translation_cvcam=[0.00949587 0.00473047 0.0066598 ], sc_factor=8.091687041886944
[bundlesdf.py] First nerf run, create Runner, latest nerf frame 1668813028705557007
[nerf_runner.py] Octree voxel dilate_radius:1
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mona/BundleSDF/bundlesdf.py", line 219, in run_nerf
    nerf = NerfRunner(cfg_nerf,rgbs,depths=depths,masks=masks,normal_maps=normal_maps,occ_masks=occ_masks,poses=poses,K=K,build_octree_pcd=pcd_normalized)
  File "/home/mona/BundleSDF/nerf_runner.py", line 156, in __init__
    self.create_nerf()
  File "/home/mona/BundleSDF/nerf_runner.py", line 208, in create_nerf
    embed_fn, input_ch = get_embedder(self.cfg['multires'], self.cfg, i=self.cfg['i_embed'], octree_m=self.octree_m)
  File "/home/mona/BundleSDF/nerf_helpers.py", line 207, in get_embedder
    from mycuda.torch_ngp_grid_encoder.grid import GridEncoder
  File "/home/mona/BundleSDF/mycuda/torch_ngp_grid_encoder/grid.py", line 23, in <module>
    import gridencoder
ModuleNotFoundError: No module named 'gridencoder'
^CTraceback (most recent call last):
  File "run_custom.py", line 203, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 103, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/mona/BundleSDF/bundlesdf.py", line 579, in run
    time.sleep(0.01)
KeyboardInterrupt
[2023-06-22 19:05:51.635] [warning] [Bundler.cpp:59] Destructor
```

**Comment by monajalal** [comment]
very hacky solution but works
```
138  cd mycuda/
  141  python setup.py build_ext --inplace
  143  export PYTHONPATH=$PYTHONPATH:/home/mona/BundleSDF/mycuda
  145  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/conda/envs/py38/lib/python3.8/site-packages/torch/lib
```

**Comment by qiaoyaya2011** [comment]
it does not work,


> 138  cd mycuda/
>   141  python setup.py build_ext --inplace
>   143  export PYTHONPATH=$PYTHONPATH:/home/mona/BundleSDF/mycuda
>   145  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/conda/envs/py38/lib/python3.8/site-packages/torch/lib

**Comment by qiaoyaya2011** [comment]
557007 
[2024-11-25 18:31:05.018] [warning] [Bundler.cpp:920] OptimizerGPU begin, global_corres#=3003
global_corres=3003
maxNumResiduals / maxNumberOfImages = 51003 / 5 = 10200
m_maxNumberOfImages*m_maxCorrPerImage = 5 x 1326 = 6630
m_solver->solve Time difference = 4.72[ms]
[2024-11-25 18:31:05.024] [warning] [Bundler.cpp:924] OptimizerGPU finish
[2024-11-25 18:31:05.025] [warning] [Bundler.cpp:320] Added frame 1668813028705557007 as keyframe, current #keyframe: 5
[bundlesdf.py] processNewFrame done 1668813028705557007
[bundlesdf.py] 1668813028705557007 prepare data for nerf
[bundlesdf.py] out_dir: /home/qiao/project/BundleSDF/output_1126_milk//1668813028705557007/nerf
[tool.py] compute_scene_bounds_worker start
[tool.py] compute_scene_bounds_worker done
[tool.py] merge pcd
[tool.py] compute_translation_scales done
translation_cvcam=[0.00946481 0.00484476 0.00668196], sc_factor=8.096200666223805
[bundlesdf.py] First nerf run, create Runner, latest nerf frame 1668813028705557007
[nerf_runner.py] Octree voxel dilate_radius:1
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qyy/project/BundleSDF/bundlesdf.py", line 219, in run_nerf
    nerf = NerfRunner(cfg_nerf,rgbs,depths=depths,masks=masks,normal_maps=normal_maps,occ_masks=occ_masks,poses=poses,K=K,build_octree_pcd=pcd_normalized)
  File "/home/qyy/project/BundleSDF/nerf_runner.py", line 156, in __init__
    self.create_nerf()
  File "/home/qyy/project/BundleSDF/nerf_runner.py", line 208, in create_nerf
    embed_fn, input_ch = get_embedder(self.cfg['multires'], self.cfg, i=self.cfg['i_embed'], octree_m=self.octree_m)
  File "/home/qyy/project/BundleSDF/nerf_helpers.py", line 207, in get_embedder
    from mycuda.torch_ngp_grid_encoder.grid import GridEncoder
  File "/home/qyy/project/BundleSDF/mycuda/torch_ngp_grid_encoder/grid.py", line 23, in <module>
    import gridencoder
ModuleNotFoundError: No module named 'gridencoder'
