### ISSUE TITLE
libGL error: 

### ISSUE THREAD

**Issue by ZisongXu** [NVlabs/BundleSDF#73]
Hi Dear:

Thanks for your nice project! When I tried to run the milk example, I got the following error:

```
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
Glfw Error 65543: GLX: Failed to create context: GLXBadFBConfig
```

I've actually run milk example before and it worked perfectly fine, I can see the window that pops up after running the code (modelling of milk). After that I went into the "XMem" code to learn how to generate mask images (I did not modify the contents of the BundleSDF, I created a new singularity container myself and completed the XMem code there). After generating the mask images successfully, I went back to the BundleSDF code and wanted to run my own example (I did not change anything in the docker container), and then got that error. Do you have any idea about that?

Thanks a lot!

Best Regards

**Comment by ZisongXu** [comment]
I saw that you said use `--use_gui 0`, and then I got new errors:

```
[acceleratesupport.py] No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
Traceback (most recent call last):
  File "run_custom.py", line 204, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 107, in run_one_video
    run_one_video_global_nerf(out_folder=out_folder)
  File "run_custom.py", line 152, in run_one_video_global_nerf
    tracker.run_global_nerf(reader=reader, get_texture=True, tex_res=512)
  File "/home/sc19zx/docker/BundleSDF/bundlesdf.py", line 763, in run_global_nerf
    mesh = nerf.mesh_texture_from_train_images(mesh, rgbs_raw=rgbs_raw, train_texture=False, tex_res=tex_res)
  File "/home/sc19zx/docker/BundleSDF/nerf_runner.py", line 1490, in mesh_texture_from_train_images
    renderer = ModelRendererOffscreen([], cam_K=self.K, H=self.H, W=self.W, zfar=self.cfg['far']*self.cfg['sc_factor'])
  File "/home/sc19zx/docker/BundleSDF/offscreen_renderer.py", line 59, in __init__
    self.r = pyrender.OffscreenRenderer(self.W, self.H)  #!NOTE version>0.1.32 not work https://github.com/mmatl/pyrender/issues/85
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/offscreen.py", line 137, in _create
    egl_device = egl.get_device_by_index(device_id)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
    raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)
Process Process-4:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sc19zx/docker/BundleSDF/bundlesdf.py", line 89, in run_nerf
    join = p_dict['join']
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-08-15 09:03:28.313] [warning] [Bundler.cpp:59] Destructor
[2023-08-15 09:03:28.316] [warning] [Bundler.cpp:59] Destructor
```

I do not know why the code has suddenly become like this, when it's clearly not doing anything.

**Comment by zhujingsong** [comment]
> I saw that you said use `--use_gui 0`, and then I got new errors:
> 
> ```
> [acceleratesupport.py] No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
> Traceback (most recent call last):
>   File "run_custom.py", line 204, in <module>
>     run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
>   File "run_custom.py", line 107, in run_one_video
>     run_one_video_global_nerf(out_folder=out_folder)
>   File "run_custom.py", line 152, in run_one_video_global_nerf
>     tracker.run_global_nerf(reader=reader, get_texture=True, tex_res=512)
>   File "/home/sc19zx/docker/BundleSDF/bundlesdf.py", line 763, in run_global_nerf
>     mesh = nerf.mesh_texture_from_train_images(mesh, rgbs_raw=rgbs_raw, train_texture=False, tex_res=tex_res)
>   File "/home/sc19zx/docker/BundleSDF/nerf_runner.py", line 1490, in mesh_texture_from_train_images
>     renderer = ModelRendererOffscreen([], cam_K=self.K, H=self.H, W=self.W, zfar=self.cfg['far']*self.cfg['sc_factor'])
>   File "/home/sc19zx/docker/BundleSDF/offscreen_renderer.py", line 59, in __init__
>     self.r = pyrender.OffscreenRenderer(self.W, self.H)  #!NOTE version>0.1.32 not work https://github.com/mmatl/pyrender/issues/85
>   File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
>     self._create()
>   File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/offscreen.py", line 137, in _create
>     egl_device = egl.get_device_by_index(device_id)
>   File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_index
>     raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
> ValueError: Invalid device ID (0)
> Process Process-4:
> Traceback (most recent call last):
>   File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/sc19zx/docker/BundleSDF/bundlesdf.py", line 89, in run_nerf
>     join = p_dict['join']
>   File "<string>", line 2, in __getitem__
>   File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
>     kind, result = conn.recv()
>   File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
>     buf = self._recv_bytes()
>   File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
>     buf = self._recv(4)
>   File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
>     chunk = read(handle, remaining)
> ConnectionResetError: [Errno 104] Connection reset by peer
> [2023-08-15 09:03:28.313] [warning] [Bundler.cpp:59] Destructor
> [2023-08-15 09:03:28.316] [warning] [Bundler.cpp:59] Destructor
> ```
> 
> I do not know why the code has suddenly become like this, when it's clearly not doing anything.

How do you solved this problem ??? Could you show the details?

**Comment by ZisongXu** [comment]
@zhujingsong 
I rebuilt a docker container based on the contents of the following link:

[https://github.com/NVlabs/BundleSDF/issues/15#issuecomment-1608198203](https://github.com/NVlabs/BundleSDF/issues/15#issuecomment-1608198203)

**Comment by zhujingsong** [comment]
Thanks. pip install scipy==1.8 && pip install PyOpenGL-accelerate solved my problem.
